version = 1

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"
  
  [analyzers.meta]
  max_line_length = 120

# Test coverage analyzer
[[analyzers]]
name = "test-coverage"
enabled = true
